name: MyFlow

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checking current dir
        run: pwd
      - name: current folder files
        run: ls -ltr
      - name: checking packages status
        run: which docker git terraform python tree    